name: Notify Slack on release commits

on:
  push:
    branches:
      - release

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Set commit metadata
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV
          echo "AUTHOR_NAME=${{ github.event.head_commit.author.name }}" >> $GITHUB_ENV

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.ENG_OPS_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":cat: *New commit pushed to `release`* in *${{ github.repository }}*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ env.AUTHOR_NAME }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n`${{ env.SHORT_SHA }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Message:*\n${{ github.event.head_commit.message }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ env.COMMIT_URL }}|View commit>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
